version: "2"
services:
  app:
    container_name: pm_system
    restart: always
    build: .
    ports:
      - "8888:8080"
    links:
      - mongo
    volumes:
        - '.:/app'
    depends_on:
        - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

